apps/house/urls.py
from django.conf.urls import url
from . import views
app_name='house'
urlpatterns=[
		url(r'^$',views.index,name='index'),
		url(r'^login_reg$',views.login_reg,name='login_reg'),
        url(r'^registration$',views.registration,name='register'),
        url(r'^login$',views.login,name='login'),
        url(r'^display$',views.display,name='display'),
        ]

buynewhouse/urls.py
from django.conf.urls import url,include
# from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^',include('apps.house.urls'))
]

apps/house/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt


from django.db import models

email_reg=re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
name_reg=re.compile(r'^[A-Za-z]{2,}$')
pin_reg=re.compile(r'^.{8,}$')
username_reg=re.compile(r'^[0-9a-zA-Z?-]{8,}$')

class UserManager(models.Manager):
    
    def register_valid(self,first,last,email,pin,confirm,username):
        error=[]
        if not name_reg.match(first):
            error.append("first name invalid")
        if not name_reg.match(last):
            error.append("last name invalid")
        if not email_reg.match(email):
            error.append("email invalid")
        if not pin_reg.match(pin):
            error.append("password too short")
        if pin!=confirm:
            error.append("confirm don't match with password")
        if not username_reg.match(username):
            error.append("username invalid")
        if User.objects.isExist(username):
            error.append("username is used, please choose a new one")
        return error

    def isExist(self,username):
        return User.objects.filter(username=username).exists()
    
    def login_valid(self,username,password):
        hashedpw=User.objects.get(username=username).password.encode()
        if bcrypt.hashpw(password.encode(),hashedpw)==hashedpw:
            return True
        else:
            return False

class User(models.Model):
    first_name=models.CharField(max_length=30)
    last_name=models.CharField(max_length=30)
    username=models.CharField(max_length=30,null=True)
    email=models.CharField(max_length=50)
    password=models.CharField(max_length=255)
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)
    objects=UserManager()


class PublicHousingAuthorities(models.Model):
    x = models.FloatField(db_column='X', blank=True, null=True)  # Field name made lowercase.
    y = models.FloatField(db_column='Y', blank=True, null=True)  # Field name made lowercase.
    formal_participant_name = models.TextField(db_column='FORMAL_PARTICIPANT_NAME', blank=True, null=True)  # Field name made lowercase.
    ha_phn_num = models.BigIntegerField(db_column='HA_PHN_NUM', blank=True, null=True)  # Field name made lowercase.
    ha_email_addr_text = models.TextField(db_column='HA_EMAIL_ADDR_TEXT', blank=True, null=True)  # Field name made lowercase.
    phas_designation = models.TextField(db_column='PHAS_DESIGNATION', blank=True, null=True)  # Field name made lowercase.
    ha_low_rent_size_category = models.TextField(db_column='HA_LOW_RENT_SIZE_CATEGORY', blank=True, null=True)  # Field name made lowercase.
    ha_program_type = models.TextField(db_column='HA_PROGRAM_TYPE', blank=True, null=True)  # Field name made lowercase.
    total_units = models.IntegerField(db_column='TOTAL_UNITS', blank=True, null=True)  # Field name made lowercase.
    total_occupied = models.IntegerField(db_column='TOTAL_OCCUPIED', blank=True, null=True)  # Field name made lowercase.
    pct_occupied = models.FloatField(db_column='PCT_OCCUPIED', blank=True, null=True)  # Field name made lowercase.
    pha_total_units = models.IntegerField(db_column='PHA_TOTAL_UNITS', blank=True, null=True)  # Field name made lowercase.
    spending_per_month = models.IntegerField(db_column='SPENDING_PER_MONTH', blank=True, null=True)  # Field name made lowercase.
    chldrn_mbr_cnt = models.IntegerField(db_column='CHLDRN_MBR_CNT', blank=True, null=True)  # Field name made lowercase.
    eldly_prcnt = models.FloatField(db_column='ELDLY_PRCNT', blank=True, null=True)  # Field name made lowercase.
    pct_disabled_lt62_all = models.FloatField(db_column='PCT_DISABLED_LT62_ALL', blank=True, null=True)  # Field name made lowercase.
    pct_lt80_median = models.FloatField(db_column='PCT_LT80_MEDIAN', blank=True, null=True)  # Field name made lowercase.
    median_inc_amnt = models.IntegerField(db_column='MEDIAN_INC_AMNT', blank=True, null=True)  # Field name made lowercase.
    curcnty_nm = models.TextField(db_column='CURCNTY_NM', blank=True, null=True)  # Field name made lowercase.
    std_addr = models.TextField(db_column='STD_ADDR', blank=True, null=True)  # Field name made lowercase.
    std_city = models.TextField(db_column='STD_CITY', blank=True, null=True)  # Field name made lowercase.
    std_st = models.TextField(db_column='STD_ST', blank=True, null=True)  # Field name made lowercase.
    std_zip5 = models.IntegerField(db_column='STD_ZIP5', blank=True, null=True)  # Field name made lowercase.
    lat = models.FloatField(db_column='LAT', blank=True, null=True)  # Field name made lowercase.
    lon = models.FloatField(db_column='LON', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Public_Housing_Authorities'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class HouseUser(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    username = models.CharField(max_length=30, blank=True, null=True)
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'house_user'

apps/house/views.py
from .models import PublicHousingAuthorities as ph
from django.shortcuts import render,redirect,reverse
from .models import User , UserManager
from django.contrib import messages
# Create your views her e.
import bcrypt
statedict={
' LABAMA': 'AL',
'ALASKA': 'AK',
'ARIZONA': 'AZ',
'ARKANSAS': 'AR',
'CALIFORNIA': 'CA',
'COLORADO': 'CO',
'CONNECTICUT': 'CT',
'DELAWARE': 'DE',
'FLORIDA': 'FL',
'GEORGIA': 'GA',
'HAWAII': 'HI',
'IDAHO': 'ID',
'ILLINOIS': 'IL',
'INDIANA':'IN',
'IOWA': 'IA',
'KANSAS': 'KS',
'KENTUCKY': 'KY',
'LOUISIANA': 'LA',
'MAINE': 'ME',
'MARYLAND': 'MD',
'MASSACHUSETTS': 'MA',
'MICHIGAN': 'MI',
'MINNESOTA': 'MN',
'MISSISSIPPI': 'MS',
'MISSOURI': 'MO',
'MONTANA': 'MT',
'NEBRASKA': 'NE',
'NEVADA': 'NV',
'NEW HAMPSHIRE': 'NH',
'NEW JERSEY': 'NJ',
'NEW MEXICO': 'NM',
'NEW YORK': 'NY',
'NORTH CAROLINA': 'NC',
'NORTH DAKOTA': 'ND',
'OHIO': 'OH',
'OKLAHOMA': 'OK',
'OREGON': 'OR',
'PENNSYLVANIA': 'PA',
'RHODE ISLAND': 'RI',
'SOUTH CAROLINA': 'SC',
'SOUTH CAROLINA':'SC',
'SOUTH DAKOTA': 'SD',
'TENNESSEE': 'TN',
'TEXAS': 'TX',
'UTAH': 'UT',
'VERMONT': 'VT',
'VIRGINIA': 'VA',
'WASHINGTON': 'WA',
'WEST VIRGINIA': 'WV',
'WISCONSIN': 'WI',
'WYOMING': 'WY',
        }

def index(request):
    query="select id, X from Public_Housing_Authorities where STD_ST = 'WI';"
    allnames=[f.name for f in ph._meta.get_fields()]
    data=ph.objects.raw(query)
    print(data[0].x)
    return render(request,"house/index.html")

def login_reg(request):
    return render(request,"house/login.html")

def registration(request):
    if request.method=="POST":
        first=request.POST['first']
        last=request.POST['last']
        username=request.POST['username']
        email=request.POST['email']
        pin=request.POST['pin']
        confirm=request.POST['confirm']
        errors=User.objects.register_valid(first,last,email,pin,confirm,username)
        if len(errors)>0:
            print(errors)
            for error in errors:
                messages.error(request,error)
            return redirect(reverse('house:login_reg'))
        else:
            hashed=bcrypt.hashpw(pin.encode(),bcrypt.gensalt())
            user=User.objects.create(first_name=first,last_name=last,username=username,email=email,password=hashed)
        return redirect(reverse('house:display'))
 
def login(request):
    if request.method=="POST":
        login_username=request.POST['username_login']
        login_pin=request.POST['pin_login']
        if User.objects.isExist(login_username):
            if User.objects.login_valid(login_username,login_pin):

                return redirect(reverse('house:display'))
            else:
                messages.error(request,"login unsuccessful")
        else:
            messages.error(request,"user not exist")
        return redirect(reverse('house:login_reg'))

def display(request):
    if request.method=="POST":
        state=request.POST['search']
        query="select id, X, Y, FORMAL_PARTICIPANT_NAME, STD_ADDR,HA_PROGRAM_TYPE,STD_CITY,HA_PHN_NUM ,STD_ZIP5 from Public_Housing_Authorities where STD_ST = '{}';".format(statedict[state])
        data=ph.objects.raw(query)[:10]
        first=data[0]
        context={'location':data,'first1':first}
        
    else:
        context={}
    return render(request,'house/success.html',context)

apps/house/templates/house/header.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

apps/house/templates/house/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Home Page</title>
	{%load staticfiles%}	
	<link rel="stylesheet" href="{%static 'house/css/style.css'%}" media="all">


</head>



<div class="container">
	<div class="header">
		<h1>BuyA<span style="color:tomato">House</span></h1>
		<div class="nav">
			<a name= "backtotop" href="">Home</a>
			<a href="#AboutUs">About Us</a>
			<a href="#ContactUs">Contact Us</a>
			
		</div>
		<div class="login">
			<a class="contact" href="/login_reg">Login</a>
			<a class="contact" href="/login_reg">Registration</a>
		</div>
	</div>
	<hr>
	<div class="main_content">
	<img src="{% static 'house/images/house.jpg' %}" width="820px">
	<!-- <img src="house.jpg" alt="house" width="820px" > -->
		
	</div>

	<div class="infoBG">
		<a name="AboutUs" class="contact"></a>
		<a href="#backtotop" class="contact" id="back1">back to top &uarr;</a>
				<h2 name="AboutUs">About Us</h2>
		<p>Our app provides current information about single- and multi-family homes and farms and ranches for sale by the U.S. Federal Government. These previously owned properties are for sale by public auction or other method depending on the property. Anyone can buy a home for sale by the U.S. Government, but you must work with a real estate agent, broker, or servicing representative to submit an offer or bid. </p>
	</div>


	<div class="infoBG">
		<a name="ContactUs" class="contact"></a>
		<a href="#backtotop" class="contact" id="back2">back to top &uarr;</a>
		<h2 name="ContactUs">Contact Us</h2>
		<address>
			<p>Phone: (425) 223-5584</p>
			<p>Email: buyahouse@gmail.com</p>
			<p>Address: 1920 Zanker Rd #20, San Jose, CA 95112</p>
			
		</address>
		
		<div id="googleMap1" style="width:100%;height:300px;"></div>
		<br>
		<div id="googleMap2" style="width:100%;height:300px;"></div>
		
	</div>
	
	<div class="footer">
	<hr>
	BuyAHouse / buyahouse@gmail.com / © 2016 BuyAHouse. Proudly created by buyAHouse team
	<a href="#backtotop" class="contact" id="back3">back to top &uarr;</a>
		
	</div>
</div> <!--end of container -->

<script>
function myMap() {
  var mapOptions1 = {
    center: new google.maps.LatLng(37.3754,-121.9102),
    zoom:18,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var mapOptions2 = {
    center: new google.maps.LatLng(37.3754,-121.9102),
    zoom:18,
    mapTypeId: google.maps.MapTypeId.SATELLITE
  };
  
  var map1 = new google.maps.Map(document.getElementById("googleMap1"),mapOptions1);
  var marker = new google.maps.Marker({
	  position: new google.maps.LatLng(37.3754,-121.9102),
	  map: map1,
	  title: 'Dojo'
	  });
  var map2 = new google.maps.Map(document.getElementById("googleMap2"),mapOptions2);
  var marker = new google.maps.Marker({
	  position: new google.maps.LatLng(37.3754,-121.9102),
	  map: map2,
	  title: 'Dojo'
	  });
  
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?callback=myMap"></script>

</body>
</html>

apps/house/templates/house/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login & Reg | Home</title>
	{% include './header.html' %}
	{%load staticfiles%}
	<link rel="stylesheet" href="{%static 'house/css/bootstrap.min.css'%}" media="all">
	<link rel="stylesheet" href="{%static 'house/css/style.css'%}" media="all">
	<link rel="stylesheet" href="{% static 'house/static/house/images' %}" media="screen" title="no title"  charset="utf-8">

</head>
<body>

	<div class="container" id="box1">
	
		<h1>BuyA<span style="color:tomato">House</span></h1><br>
	<div class="nav">
			<a href="/">Home</a>
			<a href="/">About Us</a>
			<a href="/">Contact Us</a>
			
		</div>
	<hr>
	
	
	
		<div class="row" id="box4">
		<div class="center-block">
			<div class="well span6 offset2" id="box5">
				<h1>Log In</h1>
				<form action="{%url 'house:login'%}" method="post">
					{%csrf_token%}
					<div class="style">
						<label for="username_login">Username</label>
						<input type="text" id="username_login" name="username_login" class="form-control">
					</div>
					<div class="style">
						<label for="pin_login">Password</label>
						<input id="pin_login" type="password" name="pin_login" class="form-control">
					</div>
					<input type="submit" value="Login" class="btn btn-success">
				</form>

			</div>
		<div class="row" id="box2">
		<div class="center-block">
				<div class="well span6 offset2" id="box3">
				<h1>Sign Up</h1>
				<form action="{%url 'house:register'%}" method='post' class="form-stacked">
					{%csrf_token%}
					<div class="style">
						<label for="first">First Name</label>
						<input type="text" id="first" name="first" class="form-control">
					</div>
					<div class="style">
						<label for="last">Last Name</label>
						<input type="text" id="last" name="last" class="form-control">
					</div>
					<div class="style">
						<label for="username">Username</label>
						<input type="text" id="username" name="username" class="form-control">
					</div>
					<div class="style">
						<label for="email">Email</label>
						<input type="email" id="email" name="email"  class="form-control">
					</div>
					<div class="style">
						<label for="pin">Password</label>
						<input type="password" id="pin" name="pin" class="form-control">
					</div>
					<div class="style">
						<label for="confirm">Confirm pw</label>
						<input type="password" id="confirm" name="confirm" class="form-control">
					</div>
					<input type="submit" value="Register" class="btn btn-success">
				</form>

			</div>

		</div>

			
		</div>
			<button onclick="myFacebookLogin()" class="facebook">
						<img src="{% static 'house/images/fb.png' %}" width="30px">
			Login with Facebook
			</button>
			</div>
			<div class="footer">
	<hr>
	BuyAHouse / buyahouse@gmail.com / © 2016 BuyAHouse. Proudly created by buyAHouse team
	<!-- <a href="#backtotop" class="contact" id="back3">back to top &uarr;</a> -->
		
	</div>
			<!--flash some errors on the right side-->	
			{%if messages%}
			<div class="col-lg-5">
			{%for message in messages%}
				<p class="error">error: {{message}}</p>
			{%endfor%}
			</div>
			{%endif%}
	


		</div>
	
	</div>


	<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1689979144663616',
      xfbml      : true,
      version    : 'v2.8'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>
<script>
// Only works after `FB.init` is called
function myFacebookLogin() {
  FB.login(function(){}, {scope: 'publish_actions'});
}
</script>

</body>
</html>

apps/house/templates/house/success.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Login and Reg | Succcess</title>
	{%load staticfiles%}
	<link rel="stylesheet" href="{%static 'house/css/style.css'%}" media="all">
   <style>
	#map{
	height:400px;
	width:100%;
}
			
</style>
</head>
<body>
	<div class="container">
		<div class="header">
			<h1>BuyA<span style="color:tomato">House</span></h1>
				
			
			<div class="logout">
				<a class="contact" href="/">Logout</a>
			</div>
			
		</div><!--end of div header-->
		<hr>
		<div class="main_content">
			<h1>Welcome</h1>
			<h2>Find your home</h2>
			<form action={%url 'house:display'%} method='post'>
				{%csrf_token%}
				<input type="text" name="search" placeholder="Enter your city.." id="autocomplete">
				<input type="submit" name="submit" value="Find">
			</form>
			<div id="info"></div>
			<h2>Browse Homes</h2>
			
			<a class="contact" href="">Alabama</a>
			<a class="contact" href="">Alaska</a>
			<a class="contact" href="">South Dakota</a>
			<a class="contact" href="">Tennessee</a>
			<a class="contact" href="">West Virginia</a>
			<a class="contact" href="">Wisconsin</a>
<div id="map"></div>
<script>
	  
      function initMap() {
		  var center_house = {lat:{{first1.y}} , lng:{{first1.x}}};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 4,
          center: center_house
        });
		{%for house in location%}

		var cent={lat:{{house.y}},lng:{{house.x}}};
        console.log(cent);
		var marker = new google.maps.Marker({
          position: cent,
          map: map
        });
		{%endfor%}
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC4vTHBephMsPZygX3N8FGMsaAAlx-GiJE&callback=initMap">
    </script>
	{%for house in location%}
	<div>
		<h2><a href="">{{house.formal_participant_name}}</a></h2>
		<h4>Housing program type: {{house.ha_program_type}}</h4>
		<p>{{house.std_addr}},{{house.std_city}},{{house.std_zip5}}</p>
	</div>
	{%endfor%}

	</body>
</html>